apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-deployment
  labels:
    app: attendance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance
  template:
    metadata:
      labels:
        app: attendance
    spec:
      containers:
      - name: attendance
        image: 20i1815/attendance-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: mongodb://mongodb://mongodb-service:27017/attendance
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  selector:
    app: attendance
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
