name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        cd Services/Attendance && npm install
        cd ../Examination && npm install
        cd ../Faculty && npm install
        cd ../Student && npm install

    - name: Run Tests
      run: |
        cd Services/Attendance && npm test
        cd ../Examination && npm test
        cd ../Faculty && npm test
        cd ../Student && npm test
